version: '3'

services:
  production:
    build: .
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 3000:8080
    environment:
      - SERVER_PORT=8080
    container_name: 
      DemoAPIs
    restart: 
      always
    command: npm run prod
  dev:
    build: .
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 3001:8080
    environment:
      - SERVER_PORT=8080
    container_name: 
      DemoAPIs-dev
    restart: 
      always
    depends_on:
      - production
    command: npm run dev

networks:
  default:
    external:
      name: DemoNetwork