version: '3'

services:
  demo-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:8080
    environment:
      - SERVER_PORT=8080
    container_name: 
      DemoAPIs
    command: npm run prod